### ISSUE TITLE
glTF アニメーションモデルの複製機能

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#102]
glTF アニメーションモデルの複製機能があると便利かも。

＜単一モデル＞
![image](https://cloud.githubusercontent.com/assets/1833979/20029283/97e53ac2-a38b-11e6-92fa-2a0059b4d781.png)

＜複製後＞
![image](https://cloud.githubusercontent.com/assets/1833979/20029286/a679d336-a38b-11e6-9285-3dfb6e587644.png)

可能であれば、モデル毎にアニメーションのタイミングをずらしたりできると良いと思われる。

**Comment by emadurandal** [comment]
すでに対応済みなのでクローズします。

**Comment by cx20** [comment]
以下のサンプルにて対応されているこを確認。

http://jsdo.it/cx20/8UbC
![image](https://cloud.githubusercontent.com/assets/1833979/20906364/0f203fee-bb8b-11e6-97ac-49c6813d6322.png)
