### ISSUE TITLE
glTF 形式のプロペラ飛行機のモデルが読み込めない

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#103]
テストプログラム
http://jsdo.it/cx20/grfJ

対象データ
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/SampleData/models/CesiumAir/Cesium_Air.gltf

![image](https://cloud.githubusercontent.com/assets/1833979/20030591/cb5049e0-a3ab-11e6-98f1-dabb56ecafa2.png)
↑ normal が読み込めていない。

![image](https://cloud.githubusercontent.com/assets/1833979/20030594/d187e3f4-a3ab-11e6-89b0-0e1854f84904.png)
↑ 5120 … BYTE のケースが足りていないのが原因の模様。

![image](https://cloud.githubusercontent.com/assets/1833979/20030597/dfa1a8a8-a3ab-11e6-9551-7874f894cf3f.png)
↑ 他の componentType のケースも必要と思われる。

**Comment by emadurandal** [comment]
すでに解決しているのでクローズします。

**Comment by cx20** [comment]
以下のサンプルにてプロペラ飛行機が読み込めることを確認。

http://jsdo.it/cx20/grfJ
![image](https://cloud.githubusercontent.com/assets/1833979/20905678/1c5f1386-bb88-11e6-99c2-b8edd5768a1d.png)
