### ISSUE TITLE
glTF Materials Common format support

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#105]
GLBoost は MaterialsCommon 形式の glTF ファイルが未対応の為、対応を希望。

http://jsdo.it/cx20/Szbr

https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common

**Comment by emadurandal** [comment]
18c6e9a31dc5b0c9e203e8b42286d79fa6a1272f にて、クラッシュせずにとりあえず表示はできるようにしました。

しかし、KHR_materials_commonに本来の意味でちゃんと対応するには、もっと工数が必要ですね。

**Comment by emadurandal** [comment]
Done.
