### ISSUE TITLE
Windows 環境で aux という名前のフォルダを作成することができない

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#106]
Windows では「nul」「con」「aux」などは予約語である為、フォルダ名に使用することができません。
お手数ですがフォルダ名の変更をお願いします。

![image](https://cloud.githubusercontent.com/assets/1833979/20636613/1c041300-b3b3-11e6-8b24-a1642b3ad302.png)

![image](https://cloud.githubusercontent.com/assets/1833979/20636580/94f7e828-b3b2-11e6-8e9e-c593096d9243.png)

**Comment by emadurandal** [comment]
`aux` -> `auxiliaries` に変更しました。
