### ISSUE TITLE
Support for cameras enclosed in glTF file

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#107]
glTF ファイルの VC.gltf（Virtual City）サンプルには、15個のカメラがプリセットされているようです。

サンプルの表現力が格段に上がりそうなので、是非、サポートをお願いします。

https://richtr.github.io/three.js/examples/webgl_loader_gltf.html

![image](https://cloud.githubusercontent.com/assets/1833979/20645601/70bbb300-b4a6-11e6-941f-4b35e971cada.png)

![image](https://cloud.githubusercontent.com/assets/1833979/20645607/aa2c1512-b4a6-11e6-86da-c5855c51101a.png)

**Comment by emadurandal** [comment]
Done.
