### ISSUE TITLE
Reflect the state setting of glTF1 correctly in GLBoost rendering.

### ISSUE THREAD

**Issue by emadurandal** [emadurandal/GLBoost#112]
It is as the title.

Especially,

* Correct handling of translucency related to glTF (check each Issue discussed in glTF github page)

**Comment by cx20** [comment]
関連
https://github.com/KhronosGroup/COLLADA2GLTF/issues/7
https://github.com/KhronosGroup/glTF/issues/576

**Comment by cx20** [comment]
https://github.com/KhronosGroup/COLLADA2GLTF/issues/7
https://github.com/KhronosGroup/glTF/issues/576

**Comment by emadurandal** [comment]
As for glTF 1.0, this issue is archeved so close it once.
