### ISSUE TITLE
glTF Duck is Dark

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#116]
GLBoost + glTF Loader を用いて Duck.gltf を読み込んだ際、表示が暗い気がします。

![image](https://cloud.githubusercontent.com/assets/1833979/21318301/f56967bc-c64b-11e6-849d-e8d76ea61e56.png)
https://cx20.github.io/gltf-test/examples/glboost/index.html?model=Duck&scale=1

JglTF Viewer で確認したところ、モデル内にライトが設定されている為、ライトが適用されていれば、暗くならないと思われます。

![image](https://cloud.githubusercontent.com/assets/1833979/21318435/7f32cfc4-c64c-11e6-8c46-34aa909cf453.png)

**Comment by cx20** [comment]
WebGL Inspector で調べたところ、ライト用の uniform 変数に正しく値が設定されていないように見受けられました。

![image](https://cloud.githubusercontent.com/assets/1833979/21318522/e7795594-c64c-11e6-9cc6-b8df52a18c4d.png)


GLBoost + glTF Loader + WebGL Inspector
![image](https://cloud.githubusercontent.com/assets/1833979/21318465/9b218f86-c64c-11e6-860e-b4d6e116d8de.png)

Three.js + glTF Loader + WebGL Inspector
![image](https://cloud.githubusercontent.com/assets/1833979/21318508/d17fbc06-c64c-11e6-9d10-00289f3b454b.png)

**Comment by cx20** [comment]
テストしていたバージョンが古かったようです。
 GLBoost 2016.12.08 → 2016.12.19 バージョンに更新したところ、表示されました。

![image](https://cloud.githubusercontent.com/assets/1833979/21323118/715bfcaa-c65f-11e6-95f3-5ce39444230a.png)
https://cx20.github.io/gltf-test/examples/glboost/index.html?model=Duck&scale=1

![image](https://cloud.githubusercontent.com/assets/1833979/21323239/e7e84662-c65f-11e6-90c9-0d90a98ae42c.png)

![image](https://cloud.githubusercontent.com/assets/1833979/21323183/a7560756-c65f-11e6-9bcd-1d29248cceb6.png)

**Comment by emadurandal** [comment]
最新版では解決できていますので、クローズします。
