### ISSUE TITLE
When Group node is in Matrix mode, Translate can not move

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#117]
Matrix モードの場合、
groupノードが、translateのベクターの値ではなくて、別に持っている行列の値を使って座標変換が行われてしまう為、translate での移動が行えない。

http://jsdo.it/cx20/Mrvv

```js
var driver = group.searchElement("technic_driver_assy-node");
driver.translate = new GLBoost.Vector3(-0.1, 0, 0); // 0 以外を設定するとドライバーが消える？
```

希望する動作：
![image](https://user-images.githubusercontent.com/1833979/43047488-d78d4e80-8e12-11e8-9587-35af4875b8c7.png)

実際の動作結果：
![image](https://user-images.githubusercontent.com/1833979/43047508-0e1b10a4-8e13-11e8-823f-9397fd4cf74f.png)

**Comment by emadurandal** [comment]
We addressed this problem by converting internally. Please check.

**Comment by emadurandal** [comment]
@cx20 How is that? Have you confirmed that it is fixed?

**Comment by cx20** [comment]
I tried again with the latest version of GLBoost.
http://jsdo.it/cx20/uteL

However, it seems that an error occurs. Is it a usage problem?
```
glboost.js:4030 
Uncaught (in promise) TypeError: Cannot read property 'rotationMatrix' of null
    at M_Group.getMatrixAtOrStatic (glboost.js:4030)
    at M_Group._multiplyMyAndParentTransformMatrices (glboost.js:4560)
    at M_Group._multiplyMyAndParentTransformMatrices (glboost.js:4568)
    at M_Mesh._multiplyMyAndParentTransformMatrices (glboost.js:4568)
    at M_Mesh.getWorldMatrixAt (glboost.js:4540)
    at DrawKickerWorld.draw (glboost.js:6427)
    at Geometry.draw (glboost.js:7563)
    at M_Mesh.draw (glboost.js:12635)
    at opacityMeshes.forEach (glboost.js:14367)
    at Array.forEach (<anonymous>)
```

For reference, I will post a link to the previous sample program.
The original problem is that you can not use `translate` to change the position of the driver.
http://jsdo.it/cx20/Mrvv

**Comment by cx20** [comment]
I confirmed that the problem was solved with the latest version of the library.

http://jsdo.it/cx20/uEy1
![image](https://user-images.githubusercontent.com/1833979/43081171-63fe2736-8ecc-11e8-96bf-8478d1c4b404.png)

```js
　var driver = group.searchElement("technic_driver_assy-node");
　var tmpVector3 = driver.translate;
　driver.translate = new GLBoost.Vector3(tmpVector3.x, tmpVector3.y, tmpVector3.z + 50.0);
```
