### ISSUE TITLE
glTF-MaterialsCommon's model is white

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#119]
In the model of glTF-MaterialsCommon without texture, the color seems to be white.

glTF-MaterialsCommon/Box.gltf
https://cx20.github.io/gltf-test/examples/glboost/index.html?category=sampleModels&model=Box&scale=1&type=glTF-MaterialsCommon

![image](https://cloud.githubusercontent.com/assets/1833979/21962533/8b18e1aa-db6b-11e6-8513-09c1f6ecf15b.png)

glTF-MaterialsCommon/Duck.gltf
http://localhost:3000/examples/glboost/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-MaterialsCommon

![image](https://cloud.githubusercontent.com/assets/1833979/21962551/a3d90774-db6b-11e6-86dc-69a51162790a.png)

**Comment by cx20** [comment]
I confirmed that it has been fixed in the latest version.

![image](https://cloud.githubusercontent.com/assets/1833979/22216048/d6d2c4dc-e1e0-11e6-9379-6d76346212d4.png)

**Comment by emadurandal** [comment]
Thanks!
