### ISSUE TITLE
SimpleTexture of glTF 1.1 is not displayed on GLBoost r2-dev

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#120]
When I tried the latest version of GLBoost, SimpleTexture was not displayed.

https://cx20.github.io/gltf-test/examples/glboost/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF

![image](https://cloud.githubusercontent.com/assets/1833979/22401611/d96657cc-e61d-11e6-91a9-6e2b81fa0f6a.png)

The following display is correct.
![image](https://cloud.githubusercontent.com/assets/1833979/22401613/04c406bc-e61e-11e6-9a8c-f01855354e22.png)

**Comment by cx20** [comment]
I confirmed that it has been fixed in the latest version.

**Comment by emadurandal** [comment]
Thanks!
