### ISSUE TITLE
Safari で glTF ファイルが読めないケースがある

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#57]
以下のサンプルが、Safari (OSX / iPhone) だと表示されない。

> [WebGL] GLBoost + glTF Loader を試してみるテスト（その１）
> http://jsdo.it/cx20/G5nJ

glTF-Embedded （Data URI Scheme ）のものがダメな感じがするが、Babylon.js だとSafari でも表示可能。

> [WebGL] Babylon.js + glTFFileLoader を試してみるテスト
> http://jsdo.it/cx20/yptM

以下は参考情報です。

＜確認した環境（GLBoostによる表示結果）＞
[OK] Windows 10 + Chrome 48.0.2564.109 m
[OK] Windows 10 + Firefox 44.0.2
[OK] Windows 10 + Microsoft Edge 25.10586.0.0(EdgeHTML 13.10586)
[OK] Windows 10 + 11.103.10586.0
[NG] Mac OSX 10.10.5 + Safari 601.2.7
[OK] Mac OSX 10.10.5 + Firefox 38.0
[OK] Mac OSX 10.10.5 + Chrome 47.0
[NG] iPhone 9.2.1 + Safari 601.1

＜使用したモデルデータ＞
> ■ glTF/sampleModels/box/glTF-Embedded/
> https://github.com/KhronosGroup/glTF/tree/master/sampleModels/box/glTF-Embedded

**Comment by emadurandal** [comment]
dde0199 にて対応しました。ご確認を〜。

**Comment by cx20** [comment]
glTF ファイル、Safari (OSX / iPhone) で表示できることを確認。

> [WebGL] GLBoost + glTF Loader を試してみるテスト（その１改2）
> http://jsdo.it/cx20/UYH9

**Comment by emadurandal** [comment]
よかったー。閉じますねー。
