### ISSUE TITLE
Could not read a texture of the Data URI Scheme form in Safari.

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#63]
Safari で Data URI Scheme 形式のテクスチャが読み込めない
Safari で下記のようにテクスチャを読み込もうとするとエラーとなる。
```
var texture = new GLBoost.Texture('data:image/jpeg;base64,/9j/4AA...');
```
実行結果
```
Cross-origin image load denied by Cross-Origin Resource Sharing policy.
```

glTF ファイルの Embedded ファイル形式の時も、同様のエラーが出ていた為、恐らく同様の対策が必要と思われる。

参考：_loadBinaryFile()

**Comment by cx20** [comment]
https://github.com/emadurandal/GLBoost/issues/94

**Comment by emadurandal** [comment]
対応したのでクローズします。
