### ISSUE TITLE
Transparent support

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#65]
箱を半透明にしたいが、ボールが隠れて見えなくなっている。

> GLBoost + Oimo.js で箱にボールを入れてみるテスト（改）
> http://jsdo.it/cx20/AndF

> glboost
> ![glboost](https://cloud.githubusercontent.com/assets/1833979/13369747/1461bd8a-dd3c-11e5-93ae-4f668b47607b.jpg)

> three.js
> ![threejs](https://cloud.githubusercontent.com/assets/1833979/13369755/3d3e450c-dd3c-11e5-9880-1d82d39dbda1.jpg)

**Comment by emadurandal** [comment]
48e1ee1 にて対応しました。

この通り。
http://jsdo.it/emadurandal/EMWE

**Comment by emadurandal** [comment]
解決したので、クローズしますねー。
