### ISSUE TITLE
Dynamic shader change support.

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#68]
動的にシェーダを変更する機能。
経過時間に応じて、SimpleShader → HalfLambertShader → PhongShader のようにシェーダを変更するようなサンプルを実現する。

**Comment by cx20** [comment]
動的にマテリアルを変更する機能。
glTF Loader で Mesh を読み込み後、specular の色を変更したいケースがあった為。

**Comment by emadurandal** [comment]
動的にシェーダーを変更するのは、コミット 077f048 で対応しました。
マテリアルについては、未確認です。もうちょっとお待ちを。

**Comment by emadurandal** [comment]
とりあえず表題のシェーダー切り替えは対応してあるので、一旦クローズします。
