### ISSUE TITLE
Bumpmap support

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#70]
表現力向上の為、バンプマップ等が使えると良いです。
- バンプマップ
- 法線マップ
- 鏡面マップ

![image](https://cloud.githubusercontent.com/assets/1833979/13378937/1e7af9a2-de5a-11e5-8376-94e0995dc4bb.png)

http://jsdo.it/cx20/vcVy
http://jsdo.it/cx20/78Dn

**Comment by emadurandal** [comment]
Done.
