### ISSUE TITLE
WebGLコンテキスト（canvas）の扱いの設計を見直す

### ISSUE THREAD

**Issue by emadurandal** [emadurandal/GLBoost#77]
以下のことについて改善します。

* 多くのクラスで、そもそものcanvasの指定の必要性をなくす

gl関数系の処理のタイミングをどうするか、という実装方針にも関わってくる問題ですね。

**Comment by cx20** [comment]
以下は参考情報です。Three.js での Multi Canvas の例になります。

> ■ three.js webgl - multiple canvases - complex
> http://threejs.org/examples/webgl_multiple_canvases_complex.html

> ■ three.js webgl - multiple canvases - grid
> http://threejs.org/examples/webgl_multiple_canvases_grid.html

**Comment by emadurandal** [comment]
three.js webgl - multiple canvases - complex

の方を見てみましたが、なるほど。うまいことやってますね。
multiple canvasの仕組み以上に、
THREE.Meshなどのクラスのコンストラクト時にはcanvasやコンテキストを引数に取らずに、

おそらく初回のレンダリング時にgl関数を読んでリソースを作っているような気がします。
（まだほとんどソース追っていないから推測ですけど）

とりあえず、 1b745cf のコミットで、

GLBoostMiddleContextクラスを導入しました。

```
var glBoostContext = new GLBoostMiddleContext(canvas);
glBoostContext.createGeometry();
```

みたいな感じで、canvasの指定はコンテキスト作成時しか必要なくなりました。
当面はこれでいきましょう。

一旦閉じますね。
