### ISSUE TITLE
複数 Canvas の際に個別にカメラを設定することができない

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#80]
scene1 / scene2 で、それぞれ camera1 / camera2 を指定したいケースがあるが
現在は、単一のカメラしか設定が行えない。

> http://jsdo.it/cx20/oUsK

**Comment by emadurandal** [comment]
こちら、解決したと思いますので。
念のため確認いただけますか？

**Comment by emadurandal** [comment]
解決とのことなので、クローズしますー。
