### ISSUE TITLE
glTF ファイルで読み込めないものがある

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#81]
テストしたコード
http://jsdo.it/cx20/C56H

読み込もうとしたモデル
![image](https://cloud.githubusercontent.com/assets/1833979/13728297/b469f4de-e956-11e5-86bf-8d40d08b28f0.png)

> ■ monster.gltf
> https://github.com/KhronosGroup/glTF/tree/master/sampleModels/monster/glTF-Embedded

**Comment by cx20** [comment]
現時点の GLBoost の glTF Loader は、Skin 未対応とのことなので、
Skin を使っている monster.gltf の再生に失敗しているのかもしれません。

**Comment by emadurandal** [comment]
対応したのでクローズします。
