### ISSUE TITLE
Camera のサンプルを分かりやすくする

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#85]
Camera に動きが無い為、サンプルの意図が伝わりにくい。

![image](https://cloud.githubusercontent.com/assets/1833979/14059340/44a213fe-f381-11e5-9c78-12a34d0c5c28.png)

**Comment by emadurandal** [comment]
970aa7a で改善しました。
プレーンの周りをカメラが回転するだけですが。
これでどうでしょ？

**Comment by cx20** [comment]
改善はしていると思うのですが・・・

パッと見、カメラではなく物体を回転しているように思う人が多い気がします。

dat.GUI.js とか使って、各種パラメータの値を表示してみるのはどうでしょう？
値が見えたほうが、カメラを使っている感が出てくる気がします。

https://workshop.chromeexperiments.com/examples/gui/#9--Updating-the-Display-Automatically

**Comment by emadurandal** [comment]
あ、それもそうですね。
ではそんな感じにさらに改善しますー。

**Comment by emadurandal** [comment]
私でなくて simiraaaa さんが改善してくれました。ありがとうございます！
あ、あれ？　私ぜんぜん働いてな…（ry


閉じますw
