### ISSUE TITLE
デバッグ用便利機能

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#86]
- XYZ軸表示機能
- グリッド表示機能

**Comment by cx20** [comment]
XYZ軸表示機能の例

```javascript
// 軸の長さ１０
var axis = new THREE.AxisHelper(10);   
// sceneに追加
scene.add(axis);
```
![image](https://cloud.githubusercontent.com/assets/1833979/14059386/b31fd5ea-f382-11e5-99fd-8dd6187d863c.png)

**Comment by cx20** [comment]
グリッド表示機能の例

```javascript
var size = 10;
var step = 1;

var gridHelper = new GLBoost.GridHelper(size, step);
scene.add(gridHelper);
```

![image](https://cloud.githubusercontent.com/assets/1833979/14059435/d81dc932-f383-11e5-84d6-cd9503617707.png)

**Comment by cx20** [comment]
実装されたことを確認しました。

■ [WebGL] GLBoost で AxisGizmo を試してみるテスト
http://jsdo.it/cx20/UpcX
![image](https://cloud.githubusercontent.com/assets/1833979/21222646/40e6a50e-c306-11e6-8853-53cd67984474.png)

■ [WebGL] GLBoost で GridGizmo を試してみるテスト
http://jsdo.it/cx20/qPZz
![image](https://cloud.githubusercontent.com/assets/1833979/21222650/506b48b8-c306-11e6-9b58-742a41ea0224.png)

**Comment by emadurandal** [comment]
クローズします。
