### ISSUE TITLE
glTF ファイルでテクスチャが Data URI 形式の場合に表示ができない

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#94]
> [WebGL] GLBoost + BoxTextured.gltf
> http://jsdo.it/cx20/8gKC

＜想定結果（Three.js + glTF Loader の読み込み例）＞
![image](https://cloud.githubusercontent.com/assets/1833979/16360336/0e86483e-3b99-11e6-8aaf-c26ebeb1e6a4.png)

＜問題箇所＞
glboost.js 8306 行目
var texture = new Texture(basePath + imageFileStr, canvas);
// basePath ... "/assets/6/t/v/g/"
// imageFileStr ... "data:imgae/png;base64,..." 

＜対応案＞
Data URI の場合は、basePath を使用しない。

＜関連＞
https://github.com/emadurandal/GLBoost/issues/57
https://github.com/emadurandal/GLBoost/issues/81

**Comment by cx20** [comment]
Safari だと Data URI の読み込みに失敗する模様。

＜問題箇所＞
https://github.com/emadurandal/GLBoost/blob/9080d457b527a84325d941f593beb6446666b37d/src/js/low_level/textures/Texture.js#L40

generateTextureFromUri() で `Cross-origin image load denied by Cross-Origin Resource Sharing policy.` のエラーが発生する。

**Comment by emadurandal** [comment]
対応済みなのでクローズします。
