### ISSUE TITLE
I want the function to obtain the animation seconds number of glTF

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#98]
glTF ファイルのモデルによって、秒数が異なる。
同じサンプルコードで、複数の glTF ファイルを表示させようとした場合、都合が悪い。

https://cx20.github.io/gltf-test/examples/glboost/index.html?model=CesiumMan&scale=1

この為、glTF ファイルのアニメーション秒数の取得が行えれば、キレイにアニメーションさせるようになると思われる。

``` javascript
    if (gtime > animTime ) {
        gtime = 0.0;
    }
```

**Comment by emadurandal** [comment]
Done.

You can use `getEndInputValueOfAnimation` method of L_Element class.
